export const roster = [
  { name: "Paul Smith", photo: "/team-photos/paul-smith.jpg" },
  { name: "Luc Marceaux", photo: "/team-photos/luc-marceaux.jpg" },
  { name: "Richard Maltby", photo: "/team-photos/richard-maltby.jpg" },
  { name: "Lazaro Tiqui", photo: "/team-photos/lazaro-tiqui.jpg" },
  { name: "Drew Hunt", photo: "/team-photos/drew-hunt.png" },
  { name: "Nathan Leupold", photo: "/team-photos/nathan-leupold.jpg" },
  { name: "Chris Kennedy", photo: "/team-photos/chris-kennedy.jpg" },
  { name: "Luke Biel", photo: "/team-photos/luke-biel.jpg" },
  { name: "Luke Smith", photo: "/team-photos/luke-smith.jpg" },
  { name: "Thomas Baca", photo: "/team-photos/thomas-baca.jpg" },
  { name: "Alex Jones", photo: "/team-photos/alex-jones.jpg" },
  { name: "Raphael Marceaux", photo: "/team-photos/raphael-marceaux.jpg" },
  { name: "Eliseo Chavez", photo: "/team-photos/eliseo-chavez.jpg" },
  { name: "Daniel Wong", photo: "/team-photos/daniel-wong.jpg" },
  { name: "Nathan Hoxworth", photo: "/team-photos/nathan-hoxworth.jpg" },
  { name: "Tommy Himelright", photo: "/team-photos/tommy-himelright.png" },
  { name: "Chris Combs", photo: "/team-photos/chris-combs.jpg" },
  { name: "Edgar Galvan", photo: "/team-photos/edgar-galvan.jpg" },
  { name: "Andrew Wong", photo: "/team-photos/andrew-wong.jpg" },
  { name: "Jair Garcia", photo: "/team-photos/jair-garcia.jpg" },
  { name: "Micah Wong", photo: "/team-photos/micah-wong.jpg" },
  { name: "Joshua Clark", photo: "/team-photos/joshua-clark.jpg" },
];
